Bp009
SynBioDex/SBOL-examples pull request #20
Opened 2022-11-11 17:17 UTC by Gonza10V

markdow from SBOL specification 3.0.1 section 7.9 and pySBOL3 example

2022-11-11 17:19 UTC, Gonza10V commented
Solves #499

2022-11-11 17:23 UTC, LukasBuecherl approved these changes
Looks good

2022-11-11 19:21 UTC, tcmitchell requested changes
The file "BP009.md" should be named "README.md" so that it displays automatically when a user clicks on the BP009 folder. See the [BP001 - BP008 PR](https://github.com/SynBioDex/SBOL-examples/pull/21) for examples.

2022-11-30 16:34 UTC, tcmitchell approved these changes

2022-11-30 16:53 UTC, merged