Best Practices 001 to 008
SynBioDex/SBOL-examples pull request #21
Opened 2022-11-11 17:22 UTC by LukasBuecherl

Added BP001 to BP008

2022-11-11 19:17 UTC, tcmitchell requested changes
Some of the markdown formatting seems off. Take a look...

2022-11-11 19:17 UTC, tcmitchell commented on SBOL/best-practices/BP002/README.md
> +\<parent_url\>/\<child_type\>\<child_type_counter\>" where the \<parent_url\> refers to the URL of the parent object, the \<child_type\> refers to the SBOL class of the child object, and \<child_type
The formatting gets wonky here. Can this be improved? Look at how this markdown renders on the branch.

2022-11-11 19:17 UTC, tcmitchell commented on SBOL/best-practices/BP006/README.md
> +For example, *Component* *Component types*, such as DNA or protein, are described using Systems Biology Ontology (SBO) terms. Similarly, the *roles* of a DNA or RNA *Component* are described via Sequ
The `\ref` at the end of this line looks like LaTeX. Can that be replaced by something else?

2022-11-11 19:17 UTC, tcmitchell commented on SBOL/best-practices/BP006/README.md
> +***
This table does not render properly as a markdown table. Look at how this renders the branch. Can this be improved?

2022-11-16 16:37 UTC, LukasBuecherl commented on SBOL/best-practices/BP002/README.md
> +\<parent_url\>/\<child_type\>\<child_type_counter\>" where the \<parent_url\> refers to the URL of the parent object, the \<child_type\> refers to the SBOL class of the child object, and \<child_type
Updated as discussed to use forward quotes

2022-11-16 16:38 UTC, LukasBuecherl commented on SBOL/best-practices/BP006/README.md
> +For example, *Component* *Component types*, such as DNA or protein, are described using Systems Biology Ontology (SBO) terms. Similarly, the *roles* of a DNA or RNA *Component* are described via Sequ
Fixed that. Must have missed it the first time

2022-11-16 16:39 UTC, LukasBuecherl commented on SBOL/best-practices/BP006/README.md
> +***
Maybe. To be honest, I don't know how to render tables properly. Googling around I found external scripts to install but I wasn't sure how to do that

2022-11-30 16:25 UTC, cjmyers commented
@jakebeal Can you have a look at BP 002?  In the PR to change from URI to IRI, you changed URI to URL in this best practice.  Should this have been changed to IRI?  If not, why?

2022-11-30 16:25 UTC, tcmitchell commented on SBOL/best-practices/BP006/README.md
> +***
See https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-tables#creating-a-table

2022-11-30 16:50 UTC, tcmitchell approved these changes

2022-11-30 16:55 UTC, Gonza10V approved these changes
Great work everyone

2022-11-30 16:55 UTC, merged